name: ロゴ追加リクエスト
description: 放送局ロゴの追加リクエストに使用してください。
title: "[ロゴ追加] {チャンネル名を入力してください}"
labels:
  - enhancement
assignees:
  - SlashNephy
body:
  - type: input
    id: channel-name
    attributes:
      label: チャンネル名
    validations:
      required: true
  - type: dropdown
    id: channel-type
    attributes:
      label: チャンネルタイプ
      options:
        - GR (地上波)
        - GR (CATV)
        - BS
        - CS
        - SKY
    validations:
      required: true
  - type: input
    id: service-id
    attributes:
      label: サービス ID
      description: 10進数で入力してください。不明な場合は http://soranikakaruhashi.blog.fc2.com/blog-entry-71.html で調べてください。
    validations:
      required: true
  - type: input
    id: region
    attributes:
      label: 放送地域
    validations:
      required: true
  - type: input
    id: logo-file
    attributes:
      label: ロゴファイル URL
      description: .svg 画像 または 512x512 以上の .png / .jpg 画像への URL を入力してください。
    validations:
      required: true
