name: latest

on:
  push:
    paths-ignore:
      - '*.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        platform:
          - x64
          - x86

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild
        run: msbuild TvTestRPC.sln -property:Configuration="Release" -property:Platform="${{ matrix.platform }}" -m

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts -ItemType Directory
          Copy-Item -Path ${{ matrix.platform }}/Release/TvTestRPC.tvtp -Destination Artifacts/
          Copy-Item -Path TvTestRPC.ini -Destination Artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TvTestRPC_${{ matrix.platform }}
          if-no-files-found: error
          path: Artifacts/

      - name: Create Release
        shell: powershell
        if: startsWith(github.ref, 'refs/tags/')
        run: Compress-Archive -Path Artifacts/* -DestinationPath TvTestRPC_${{ matrix.platform }}.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: TvTestRPC_${{ matrix.platform }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
